Fix overflow of text and formatted student and lesson feedback messages
AY2122S1-CS2103T-W16-3/tp pull request #219
Opened 2021-11-01 12:46 UTC by dt-td

2021-11-04 07:46 UTC, wpinrui requested changes
Can have a method to handle the appending of newlines

2021-11-04 07:46 UTC, wpinrui commented on src/main/java/tutoraid/logic/commands/AddStudentsToLessonsCommand.java
> +        StringBuilder namesOfStudents = new StringBuilder();
I think this may violate SLAP

2021-11-04 07:46 UTC, wpinrui commented on src/main/java/tutoraid/logic/commands/DeleteStudentsFromLessonsCommand.java
> +        StringBuilder namesOfStudents = new StringBuilder();
Same for this

2021-11-05 02:46 UTC, wpinrui approved these changes
LGTM

2021-11-05 02:46 UTC, wpinrui commented on src/main/java/tutoraid/logic/commands/AddStudentToLessonCommand.java
> +     * Constructs an AddStudentToLessonsCommand.
Should be AddStudentToLesson (without the s)

2021-11-05 03:18 UTC, JunWei3112 approved these changes
Works well! Once the above mentioned issue by @wpinrui has been fixed, LGTM!

2021-11-05 03:24 UTC, merged